version: "3.8"

services:
  backend-api:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.backend
      # args:
      #   some-arg: 1
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
