name: test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  repository_dispatch:
    types: [run_workflow]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test && flake8"

      - name: Check running containers
        run: docker ps -a

      - name: Set up Python 3.9
        id: set-up-python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Cache pipenv
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Check context variables
        id: steps
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: |
          echo "Steps context: $STEPS_CONTEXT"
          echo "steps.cache-pipenv.outcome: ${{ steps.cache-pipenv.outcome }}"
          echo $GITHUB_WORKSPACE
          ls
